openapi: 3.0.0
info:
  title: ActTrader API - OpenAPI 3.0
  description: |-
    This is a ActTrader API based on the OpenAPI 3.0 specification.  
  version: '1.0'
servers:
  # Added by API Auto Mocking Plugin
  - description: test.3 platform endpoint
    url: http://stest-01.sysfx.com:10013/
  - description: test.5 platform endpoint
    url: http://stest-01.sysfx.com:10113/
tags:
  - name: Instruments
    description: ""
  - name: Operations
    description: ""
  - name: Users
    description: ""
paths:
  /accounts:
    get:
      tags:
        - Users
      summary: method to get user accounts
      description: Get accounts list
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountList'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponce'
          description: An unexpected error response.
      security:
        - Bearer: []
  /shifts:
    get:
      tags:
        - Users
      summary: method to get user shifts
      description: Get trader shifts
      parameters:
      - name: "userid"
        in: query
        description: "Numeric ID of the user"
        required: false
        schema:
            type: integer
      - name: "instrumentid"
        in: query
        description: "Numeric ID of the instrument"
        required: false
        schema:
            type: integer
      - name: "instrumentname"
        in: query
        description: "Name of the instrument"
        required: false
        schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shifts'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponce'
          description: An unexpected error response.
      security:
        - Bearer: []

  /instruments:
    get:
      tags:
        - Instruments
      summary: method to get all instruments
      description: Get trader instruments
      parameters:
      - name: "instrument_id"
        in: query
        description: "Numeric ID of the instrument"
        required: false
        schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Instruments'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponce'
          description: An unexpected error response.
      security:
        - Bearer: []

  /trades:
    get:
      tags:
        - Operations
      summary: method to get all open positions
      description: Get trader positions
      parameters:
      - name: "account"
        in: query
        description: "Numeric ID of the account"
        required: false
        schema:
            type: integer
      - name: "trader"
        in: query
        description: "Numeric ID of the trader"
        required: false
        schema:
            type: integer
      - name: "from"
        in: query
        description: "from date"
        required: false
        schema:
            type: string
      - name: "till"
        in: query
        description: "till date"
        required: false
        schema:
            type: string
      - name: "uuid"
        in: query
        description: "next page uuid"
        required: false
        schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Positions'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponce'
          description: An unexpected error response.
      security:
        - Bearer: []
components:
  schemas:
    Account:
      type: object
      
      example: 
        accountId: 10
        balance: '10001.01'
        currency: USD
        
      properties:
        accountId:
          type: integer
        balance:
          type: string
        currency:
          type: string
          
    AccountList:
      type: object
      properties:
        data:
          items: 
            $ref: '#/components/schemas/Account'
          type: array
        success: 
          type: boolean
      example:
        success: true
        data:
          - id: 100
            balance: '10000.01'
            currency: USD
          - id: 101
            balance: '10000.01'
            currency: EUR

    Shift:
      type: object
      
      example: 
        instrument_id: 10
        bid: '0.01'
        ask: '0.01'
        distance: '0.01'
        
      properties:
        instrument_id:
          type: integer
        bid:
          type: string
        ask:
          type: string
        distance:
          type: string

    Shifts:
      type: object
      properties:
        data:
          items: 
            $ref: '#/components/schemas/Shift'
          type: array
        success: 
          type: boolean
      example:
        success: true
        data:
          - instrument_id: 1
            bid: '0.01'
            ask: '0.01'
            distance: '0.01'
          - instrument_id: 3
            bid: '0.01'
            ask: '0.01'
            distance: '0.01'

    Instrument:
      type: object
      
      example: 
        instrument_id: 10
        instrument_name: EUR/USD
        market_currency: EUR
        base_currency: USD
        contract_size: '100000'
        point_size: '0.0001'
        precision: '0.00001'
        
      properties:
        instrument_id:
          type: integer
        instrument_name:
          type: string
        market_currency:
          type: string
        base_currency:
          type: string
        contract_size:
          type: string
        point_size:
          type: string
        precision:
          type: string

    Instruments:
      type: object
      properties:
        data:
          items: 
            $ref: '#/components/schemas/Instrument'
          type: array
        success: 
          type: boolean
      example:
        success: true
        data:
          - instrument_id: 1
            instrument_name: 'EUR/USD'
            market_currency: 'EUR'
            base_currency: 'USD'
            contract_size: '10000'
            point_size: '0.0001'
            precision: '0.00001'
          - instrument_id: 2
            instrument_name: 'GBP/USD'
            market_currency: 'GBP'
            base_currency: 'USD'
            contract_size: '10000'
            point_size: '0.0001'
            precision: '0.00001'

    Position:
      type: object
      example: 
        tradeId: 10
        ticketId: 11
        accountId: 2
        pairId: 1
        amount: '10000'
        price: '1.1234'
        side: 'B'
        commission: '1.12'
        interest: '1.12'
        openTime: '2021-06-08T02:00:03Z'
        pl: '0.00001'
        commentary: "open position commentary"

      properties:
        tradeId:
          type: integer
        ticketId:
          type: integer
        accountId:
          type: integer
        pairId:
          type: integer
        amount: 
          type: string
        price: 
          type: string
        side:
          type: string
        commission:
          type: string
        interest:
          type: string
        openTime:
           type: string
        pl:
          type: string
        commentary:
          type: string
    Positions:
      type: object
      example:
        success: true
        data:
          - tradeId: 7860208
            ticketId: 7860208
            accountId: 486
            pairId: 3
            amount: '1000'
            price: '109.545'
            side: 'B'
            commission: '0'
            interest: '3.2625'
            openTime: '2021-06-10T19:30:33Z'
            pl: '123.21'
            commentary: 'text commentary'
          - tradeId: 7902689
            ticketId: 7902689
            accountId: 573
            pairId: 6
            amount: '10000'
            price: '142.005'
            side: 'S'
            commission: '-0.1'
            interest: '-14.3'
            openTime: '2022-09-22T09:56:48Z'
            pl: '-12.32'
            commentary: 'text commentary'
    errorResponce:
      example:
        success: false
        error: LOAD_FAILED
      properties:
        success:
          type: boolean
        error:
           type: string
      type: object
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer